services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        command: >
            sh -c "sleep 10 && php artisan migrate --seed && php-fpm"
        networks:
            - app-network
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: book_store
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
